[package]
name = "flake"
version = "0.1.0"
edition = "2021"
authors = ["norlen <joacim.norlen@gmail.com>"]
license = "MIT OR Apache-2.0"

[[bench]]
name = "bench"
harness = false

[dependencies]


[dev-dependencies]
criterion = "0.3"
